doc/doxygen feature complete
turtle-friends/chip8 pull request #18
Opened 2022-10-12 03:14 UTC by richardllara05

Added Doxyfile to doxygen. In order to use doxygen, doxygen must be installed through scoop.
```doxygen Doxyfile```
will generate the docs. This closes #7. Docs will need to be continually be added across the project. We will have to further discuss this.

2022-10-15 02:40 UTC, Willygilly requested changes

2022-10-15 02:40 UTC, Willygilly commented on CMakeLists.txt
> +file(GLOB SRC src/*.cc src/*.cpp)
remove .cc files and keep the .cpp files.

2022-10-15 02:40 UTC, Willygilly commented on CMakeLists.txt
> +file(GLOB INC inc/*.inc inc/*.h)
remove .cc files and keep the .h files.

2022-10-15 04:00 UTC, jaburialeh approved these changes
Looks great👍😎

2022-10-17 22:45 UTC, richardllara05 commented on .gitignore
> +!docs/Doxyfile
The '!' means "not", so it means do not ignore the Doxyfile inside of the docs folder because I had ignored the whole docs folder in line 3.

2022-10-17 23:03 UTC, merged