feat: update richardllara05 name to turtleboy00
turtle-friends/chip8 pull request #35
Opened 2023-02-11 00:25 UTC by jrbetancourt98

Closes #33

2023-02-11 00:26 UTC, turtleboy00 approved these changes

2023-02-12 02:41 UTC, jazzybear1 requested changes
Hey Junior, Looks great, but can you please update my username too? I changed it to **jazzybear1**. Thank you

2023-02-16 00:27 UTC, jazzybear1 approved these changes
Looks great👍

2023-02-16 00:28 UTC, turtleboy00 approved these changes

2023-02-16 00:30 UTC, merged